AWSTemplateFormatVersion: 2010-09-09
Description: 
  This my Cfn template for EC2 with Security Group

Resources:
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03a6eaae9938c858c
      InstanceType: t2.micro
      KeyName: secondkey
      SecurityGroupIds:
        - !Ref MySecGrp
      Tags:
        - Key: Name
          Value: !Sub Yasin ${AWS::StackName}
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          FOLDER="https://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@raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/index.html"
          cd /var/www/html
          wget https://raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/index.html
          wget https://raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/yaysin/kittens-carousel-static-website-ec2/main/static-web/cat3.png
          systemctl start httpd
          systemctl enable httpd

  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http
      GroupName: "yasinsecportfolio"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: env
          Value: dev

Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName